<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Shravani Jadhav">

<title>SteamScope Pricing Analysis: Auditing and Rebuilding a Flawed Data Pipeline</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="steam-game-pricing-analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="steam-game-pricing-analysis_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="steam-game-pricing-analysis_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="steam-game-pricing-analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="steam-game-pricing-analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="steam-game-pricing-analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="steam-game-pricing-analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="steam-game-pricing-analysis_files/libs/quarto-html/quarto-syntax-highlighting-7c69b197886ae2a34062761d21e44731.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="steam-game-pricing-analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="steam-game-pricing-analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="steam-game-pricing-analysis_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="steam-game-pricing-analysis.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">SteamScope Pricing Analysis: Auditing and Rebuilding a Flawed Data Pipeline</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Shravani Jadhav </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1><strong>Introduction</strong></h1>
<p>This project analyses Steam game pricing patterns by auditing an existing data pipeline and rebuilding it using data analytics best practices. The analysis involves reverse-engineering a legacy cleaning process, identifying data quality issues, improving the workflow, and developing a regression model to understand factors influencing game prices.</p>
</section>
<section id="part-a-forensic-data-wrangling" class="level1">
<h1><strong>Part A: Forensic Data Wrangling</strong></h1>
<section id="a1-exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="a1-exploratory-data-analysis">A1: Exploratory Data Analysis</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>raw    <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/raw_steam_games_v03.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>legacy <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/legacy_clean_v03.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(raw)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2000   14</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(legacy)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 752  17</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(raw)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [2,000 × 14] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ appid            : num [1:2000] 1e+05 1e+05 1e+05 1e+05 1e+05 ...
 $ name             : chr [1:2000] "Lone Siege" "Hollow Solstice Redux" "Stellar Dynasty III" "Radiant Genesis" ...
 $ developer        : chr [1:2000] "RedKite" "ThunderByte" "CrystalDawn" "RedKite" ...
 $ release_date     : chr [1:2000] "26/12/2021" "25/06/2023" "14/06/2024" "22/04/2022" ...
 $ genre            : chr [1:2000] "Action" "Simulation" "Action" "Action" ...
 $ genre_code       : num [1:2000] 1 4 1 1 3 1 1 2 2 4 ...
 $ price            : num [1:2000] 43.3 0 51.5 56.1 50 ...
 $ total_reviews    : num [1:2000] 0 373 0 1699 562 ...
 $ positive_ratio   : num [1:2000] 89.7 86.1 85.6 96.4 81.7 ...
 $ avg_playtime_mins: num [1:2000] 900 1143 191 909 470 ...
 $ peak_players     : num [1:2000] 253 179 467 126 462 289 318 48 203 228 ...
 $ metacritic_score : num [1:2000] NA 75 58.9 68 71 68.8 96.7 NA 85.3 98.9 ...
 $ developer_bio    : chr [1:2000] NA "Our mission: games that matter." "Passionate about narrative-driven experiences." NA ...
 $ platforms        : num [1:2000] 1 2 2 3 1 2 1 1 1 1 ...
 - attr(*, "spec")=
  .. cols(
  ..   appid = col_double(),
  ..   name = col_character(),
  ..   developer = col_character(),
  ..   release_date = col_character(),
  ..   genre = col_character(),
  ..   genre_code = col_double(),
  ..   price = col_double(),
  ..   total_reviews = col_double(),
  ..   positive_ratio = col_double(),
  ..   avg_playtime_mins = col_double(),
  ..   peak_players = col_double(),
  ..   metacritic_score = col_double(),
  ..   developer_bio = col_character(),
  ..   platforms = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(legacy)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [752 × 17] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ appid            : num [1:752] 1e+05 1e+05 1e+05 1e+05 1e+05 ...
 $ developer        : chr [1:752] "Moonlight Games" "Redkite" "Redkite" "Irongate Studios" ...
 $ release_day      : num [1:752] 6 19 9 17 22 30 14 22 4 19 ...
 $ release_month    : chr [1:752] "Nov" "Oct" "Nov" "Dec" ...
 $ release_year     : num [1:752] 2020 2019 2023 2019 2023 ...
 $ genre            : chr [1:752] "Strategy" "Action" "RPG" "Simulation" ...
 $ genre_code       : num [1:752] 3 1 2 4 4 5 4 1 5 1 ...
 $ price            : num [1:752] 40 40 40 40 40 ...
 $ total_reviews    : num [1:752] 562 966 293 435 747 948 135 624 309 405 ...
 $ positive_ratio   : num [1:752] 82 93 61 85 60 56 83 87 58 94 ...
 $ avg_playtime_mins: num [1:752] 470 652 1068 279 210 ...
 $ peak_players     : num [1:752] 462 318 203 228 88 181 79 147 121 155 ...
 $ metacritic_score : num [1:752] 71 96.7 85.3 98.9 96.8 65.1 40.3 85.6 83.3 66.5 ...
 $ platforms        : num [1:752] 1 1 1 1 3 3 1 1 2 3 ...
 $ pt_hrs           : num [1:752] 4.7 6.52 10.68 2.79 2.1 ...
 $ lpeak            : num [1:752] 6.14 5.76 5.31 5.43 4.48 5.2 4.37 4.99 4.8 5.04 ...
 $ dev_titles       : num [1:752] 101 101 101 102 85 101 107 101 101 101 ...
 - attr(*, "spec")=
  .. cols(
  ..   appid = col_double(),
  ..   developer = col_character(),
  ..   release_day = col_double(),
  ..   release_month = col_character(),
  ..   release_year = col_double(),
  ..   genre = col_character(),
  ..   genre_code = col_double(),
  ..   price = col_double(),
  ..   total_reviews = col_double(),
  ..   positive_ratio = col_double(),
  ..   avg_playtime_mins = col_double(),
  ..   peak_players = col_double(),
  ..   metacritic_score = col_double(),
  ..   platforms = col_double(),
  ..   pt_hrs = col_double(),
  ..   lpeak = col_double(),
  ..   dev_titles = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(raw)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "appid"             "name"              "developer"        
 [4] "release_date"      "genre"             "genre_code"       
 [7] "price"             "total_reviews"     "positive_ratio"   
[10] "avg_playtime_mins" "peak_players"      "metacritic_score" 
[13] "developer_bio"     "platforms"        </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(legacy)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "appid"             "developer"         "release_day"      
 [4] "release_month"     "release_year"      "genre"            
 [7] "genre_code"        "price"             "total_reviews"    
[10] "positive_ratio"    "avg_playtime_mins" "peak_players"     
[13] "metacritic_score"  "platforms"         "pt_hrs"           
[16] "lpeak"             "dev_titles"       </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(raw)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     appid            name            developer         release_date      
 Min.   :100001   Length:2000        Length:2000        Length:2000       
 1st Qu.:100501   Class :character   Class :character   Class :character  
 Median :101001   Mode  :character   Mode  :character   Mode  :character  
 Mean   :101001                                                           
 3rd Qu.:101500                                                           
 Max.   :102000                                                           
                                                                          
    genre             genre_code        price       total_reviews   
 Length:2000        Min.   :1.000   Min.   : 0.00   Min.   :   0.0  
 Class :character   1st Qu.:1.000   1st Qu.:36.74   1st Qu.: 275.8  
 Mode  :character   Median :3.000   Median :46.22   Median : 482.0  
                    Mean   :2.674   Mean   :41.17   Mean   : 507.0  
                    3rd Qu.:4.000   3rd Qu.:53.57   3rd Qu.: 716.0  
                    Max.   :5.000   Max.   :77.79   Max.   :2272.0  
                                                                    
 positive_ratio   avg_playtime_mins  peak_players    metacritic_score
 Min.   : 50.02   Min.   :  50.0    Min.   :  10.0   Min.   : 40.10  
 1st Qu.: 63.53   1st Qu.: 346.8    1st Qu.: 174.8   1st Qu.: 56.20  
 Median : 75.53   Median : 530.0    Median : 264.0   Median : 70.15  
 Mean   : 75.24   Mean   : 597.0    Mean   : 296.1   Mean   : 70.28  
 3rd Qu.: 87.18   3rd Qu.: 773.2    3rd Qu.: 383.2   3rd Qu.: 84.70  
 Max.   :100.00   Max.   :2780.0    Max.   :1090.0   Max.   :100.00  
                                                     NA's   :500     
 developer_bio        platforms    
 Length:2000        Min.   :1.000  
 Class :character   1st Qu.:1.000  
 Mode  :character   Median :2.000  
                    Mean   :1.817  
                    3rd Qu.:2.000  
                    Max.   :3.000  
                                   </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(legacy)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     appid         developer          release_day    release_month     
 Min.   :100005   Length:752         Min.   : 1.00   Length:752        
 1st Qu.:100474   Class :character   1st Qu.: 9.00   Class :character  
 Median :100989   Mode  :character   Median :16.00   Mode  :character  
 Mean   :101003                      Mean   :15.95                     
 3rd Qu.:101565                      3rd Qu.:23.00                     
 Max.   :101997                      Max.   :31.00                     
  release_year     genre             genre_code        price      
 Min.   :2018   Length:752         Min.   :1.000   Min.   :14.78  
 1st Qu.:2019   Class :character   1st Qu.:1.000   1st Qu.:40.00  
 Median :2021   Mode  :character   Median :2.000   Median :40.00  
 Mean   :2021                      Mean   :2.614   Mean   :38.78  
 3rd Qu.:2023                      3rd Qu.:4.000   3rd Qu.:40.00  
 Max.   :2024                      Max.   :5.000   Max.   :40.00  
 total_reviews    positive_ratio   avg_playtime_mins  peak_players   
 Min.   :  87.0   Min.   : 50.00   Min.   :  57.0    Min.   :  28.0  
 1st Qu.: 380.0   1st Qu.: 62.00   1st Qu.: 347.5    1st Qu.: 169.8  
 Median : 526.5   Median : 75.00   Median : 531.5    Median : 253.5  
 Mean   : 576.3   Mean   : 74.46   Mean   : 592.9    Mean   : 292.6  
 3rd Qu.: 737.0   3rd Qu.: 87.00   3rd Qu.: 770.2    3rd Qu.: 383.2  
 Max.   :1766.0   Max.   :100.00   Max.   :2196.0    Max.   :1002.0  
 metacritic_score   platforms         pt_hrs           lpeak      
 Min.   : 40.10   Min.   :1.000   Min.   : 0.570   Min.   :3.330  
 1st Qu.: 56.80   1st Qu.:1.000   1st Qu.: 3.475   1st Qu.:5.138  
 Median : 71.00   Median :2.000   Median : 5.315   Median :5.535  
 Mean   : 70.86   Mean   :1.835   Mean   : 5.929   Mean   :5.505  
 3rd Qu.: 85.40   3rd Qu.:2.000   3rd Qu.: 7.702   3rd Qu.:5.950  
 Max.   :100.00   Max.   :3.000   Max.   :21.960   Max.   :6.910  
   dev_titles    
 Min.   : 77.00  
 1st Qu.: 86.00  
 Median :101.00  
 Mean   : 95.02  
 3rd Qu.:102.00  
 Max.   :107.00  </code></pre>
</div>
</div>
</section>
<section id="a2-reconstructing-averys-pipeline" class="level2">
<h2 class="anchored" data-anchor-id="a2-reconstructing-averys-pipeline">A2: Reconstructing Avery’s Pipeline</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>student_clean <span class="ot">&lt;-</span> raw <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 1: Remove rows with zero price</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(price <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 2: Remove rows with zero reviews</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(total_reviews <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 3: Remove rows with NA values in metacritic or developer_bio</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(metacritic_score), <span class="sc">!</span><span class="fu">is.na</span>(developer_bio)) <span class="sc">|&gt;</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 4: Parse release_date and extract components</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">release_date  =</span> <span class="fu">dmy</span>(release_date),</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">release_day   =</span> <span class="fu">day</span>(release_date),</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">release_month =</span> <span class="fu">month</span>(release_date, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">TRUE</span>),</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">release_year  =</span> <span class="fu">year</span>(release_date)</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 5: Change datatype of release_month</span></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">release_month =</span> <span class="fu">as.character</span>(release_month)) <span class="sc">|&gt;</span></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 6: Standardise developer name to title case</span></span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">developer =</span> <span class="fu">str_to_title</span>(developer)) <span class="sc">|&gt;</span></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 7: Remove columns not in legacy</span></span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>name, <span class="sc">-</span>release_date, <span class="sc">-</span>developer_bio) <span class="sc">|&gt;</span></span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 8: Count developer titles (within cleaned dataset)</span></span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_count</span>(developer, <span class="at">name =</span> <span class="st">"dev_titles"</span>) <span class="sc">|&gt;</span></span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 9: Create pt_hrs (Avery divided by 100, not 60 — reproducing the bug)</span></span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pt_hrs =</span> avg_playtime_mins <span class="sc">/</span> <span class="dv">100</span>) <span class="sc">|&gt;</span></span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 10: Create lpeak = log(peak_players), rounded to 2dp</span></span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">lpeak =</span> <span class="fu">round</span>(<span class="fu">log</span>(peak_players), <span class="dv">2</span>)) <span class="sc">|&gt;</span></span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 11: Round positive_ratio to integer</span></span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">positive_ratio =</span> <span class="fu">round</span>(positive_ratio, <span class="dv">0</span>) <span class="sc">|&gt;</span> <span class="fu">as.integer</span>()) <span class="sc">|&gt;</span></span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-41"><a href="#cb17-41" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 12: Cap price at $40, then round to 2 decimal places</span></span>
<span id="cb17-42"><a href="#cb17-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">price =</span> <span class="fu">round</span>(<span class="fu">pmin</span>(price, <span class="dv">40</span>), <span class="dv">2</span>)) <span class="sc">|&gt;</span></span>
<span id="cb17-43"><a href="#cb17-43" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb17-44"><a href="#cb17-44" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-45"><a href="#cb17-45" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 13: Reorder columns to match legacy exactly</span></span>
<span id="cb17-46"><a href="#cb17-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(appid, developer, release_day, release_month, release_year,</span>
<span id="cb17-47"><a href="#cb17-47" aria-hidden="true" tabindex="-1"></a>         genre, genre_code, price, total_reviews, positive_ratio,</span>
<span id="cb17-48"><a href="#cb17-48" aria-hidden="true" tabindex="-1"></a>         avg_playtime_mins, peak_players, metacritic_score, platforms,</span>
<span id="cb17-49"><a href="#cb17-49" aria-hidden="true" tabindex="-1"></a>         pt_hrs, lpeak, dev_titles)</span>
<span id="cb17-50"><a href="#cb17-50" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-51"><a href="#cb17-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-52"><a href="#cb17-52" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(student_clean)</span>
<span id="cb17-53"><a href="#cb17-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-54"><a href="#cb17-54" aria-hidden="true" tabindex="-1"></a><span class="co"># Verify</span></span>
<span id="cb17-55"><a href="#cb17-55" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(<span class="fu">as.data.frame</span>(student_clean), <span class="fu">as.data.frame</span>(legacy))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</section>
<section id="a3-the-legacy-model" class="level2">
<h2 class="anchored" data-anchor-id="a3-the-legacy-model">A3: The Legacy Model</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the same variables as Avery</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Data object is named 'df' to match Avery's model</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> student_clean</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>legacy_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> price <span class="sc">~</span> genre_code <span class="sc">+</span> total_reviews <span class="sc">+</span> positive_ratio<span class="sc">+</span> pt_hrs <span class="sc">+</span> peak_players <span class="sc">+</span> platforms, <span class="at">data =</span> df)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(legacy_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = price ~ genre_code + total_reviews + positive_ratio + 
    pt_hrs + peak_players + platforms, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-23.3959   0.2298   0.9416   1.5455   3.0379 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    35.6700453  0.8268431  43.140  &lt; 2e-16 ***
genre_code     -0.1870398  0.0773133  -2.419  0.01579 *  
total_reviews   0.0002945  0.0004187   0.703  0.48210    
positive_ratio  0.0229455  0.0081576   2.813  0.00504 ** 
pt_hrs          0.0107251  0.0344319   0.311  0.75552    
peak_players    0.0014917  0.0006751   2.210  0.02744 *  
platforms       0.6662794  0.1488922   4.475 8.84e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.151 on 745 degrees of freedom
Multiple R-squared:  0.04853,   Adjusted R-squared:  0.04087 
F-statistic: 6.334 on 6 and 745 DF,  p-value: 1.637e-06</code></pre>
</div>
</div>
</section>
<section id="a4-the-legacy-plot" class="level2">
<h2 class="anchored" data-anchor-id="a4-the-legacy-plot">A4: The Legacy Plot</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Recreate Avery's plot exactly — including all intentional flaws:</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Facets ordered alphabetically by release_month (not calendar order)</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. genre_code treated as continuous for colour gradient (not factor)</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. $40 price cap is visible in output</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(student_clean, <span class="fu">aes</span>(<span class="at">x =</span> total_reviews, <span class="at">y =</span> price, <span class="at">colour =</span> genre_code)) <span class="sc">+</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">colour =</span> <span class="st">"blue"</span>, <span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> release_month) <span class="sc">+</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_gradient</span>(<span class="at">low =</span> <span class="st">"darkblue"</span>, <span class="at">high =</span> <span class="st">"lightblue"</span>, <span class="at">name =</span> <span class="st">"Genre Code"</span>) <span class="sc">+</span></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">title    =</span> <span class="st">"SteamScope Quarterly Report \u2014 Seed 3"</span>,</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Price vs Community Size by Release Month"</span>,</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">x        =</span> <span class="st">"Total Reviews"</span>,</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">y        =</span> <span class="st">"Price (USD)"</span></span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="steam-game-pricing-analysis_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="part-b-the-critique-version-2.0-fix" class="level1">
<h1><strong>Part B: The Critique &amp; “Version 2.0” Fix</strong></h1>
<p>To: Managing Director, SteamScope Analytics<br>
From: Shravani Jadhav<br>
Re: Auditing and Fixing of Data Pipeline</p>
<p>After analyzing the data and auditing Avery’s pipeline, we found the bad decisions she took, while not all were wrong, it was important to fix the pipeline. We ran a diagnostic check to understand how Avery’s data manipulations actively violated linear regression assumptions. We then cleaned and rebuilt the dataset properly by fixing the errors made by Avery and created a clean pipeline. We also built a new V2 model and plot and concluded by interpreting the model.</p>
<section id="b1-the-audit" class="level2">
<h2 class="anchored" data-anchor-id="b1-the-audit">B1: The Audit</h2>
<p>After careful examination of the data wrangling process implemented by Avery, I have discovered six bad practices. Not all steps are necessarily incorrect, like removing games with zero prices and zero reviews, date parsing, capitalizing the developers names, and calculating the log of peak players are all reasonable choices. The six errors which break the rules of good data science are given below.</p>
<p><strong>Error 1: Playtime divided by 100 instead of 60</strong></p>
<p>Avery knowingly divided avg_playtime_mins by 100 instead of 60 for converting minutes into hours. This creates an error of unit conversion and goes against the data integrity principle – computed columns should match reality in their value. As a result, all the values of playtime in the dataset are understated by approximately 40%. Any model for pricing based on this data, as well as any report to a client, would draw wrong conclusions regarding the relationship between player engagement and price.</p>
<p><strong>Error 2: Price arbitrarily capped at $40</strong></p>
<p>By using the pmin() function to force all prices greater than $40 to the value of $40, Avery arbitrarily truncated the top end of the price distribution without explanation, contrary to the representativeness principle that data should capture reality rather than a arbitrary limit. Out of 752 games in the cleaned dataset, 600+ were artificially set to $40, leaving the dependent variable with essentially no variation. As a result, the regression was useless, and SteamScope underestimated consumer demand for premium games by a significant amount.</p>
<p><strong>Error 3: Rows deleted based on missing metacritic_score</strong></p>
<p>By using ‘na.rm=TRUE’ in filter criteria, Avery excluded all rows for which metacritic_score had a missing value. Over 430 paid games were removed from the data in this way. Most indie games do not receive any ratings on Metacritic, so this is not a data issue, it just means the indie games are less popular. By removing these rows systematic sampling bias is introduced, violating the principle of representativeness. Because of this, SteamScope failed to analyze those indie games that most needed their help.</p>
<p><strong>Error 4: Rows deleted based on missing developer_bio</strong></p>
<p>There was no need to delete the rows with developer_bio NA values as that column was unncessary and was anyways going to be dropped. This introduces further sampling bias with no business justification. So Avery did this on purpose to create confusion. However, whole studio and all its games could be left out altogether, messing up the distribution in the study.</p>
<p><strong>Error 5: Kept genre_code as numeric</strong></p>
<p>The problem here is that instead of converting this variable into a factor, Avery uses it as a numeric one. In other words, genre_code variable is treated linearly, which is incorrect since genres can be considered as categories and do not have a linear dependence. Consequently, this causes an additional error and a biased result.</p>
<p><strong>Error 6: Converted release_month to character</strong></p>
<p>Avery converted release_month into character using ‘as.character(release_month)’, destroying its ordered structure. This meant that months were sorted alphabetically instead of chronologically during visualization and plotting. Due to this, seasonal trends in pricing and release patterns became harder to interpret data lost is structure.</p>
</section>
<section id="b2-the-diagnostic-check" class="level2">
<h2 class="anchored" data-anchor-id="b2-the-diagnostic-check">B2: The Diagnostic Check</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggResidpanel)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Run residual diagnostic panel on the legacy model</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">resid_panel</span>(legacy_model, <span class="at">plots =</span> <span class="st">"all"</span>, <span class="at">smoother =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="steam-game-pricing-analysis_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The residual diagnosticsshows that the legacy model violates essential assumptions for linear regression. The Q-Q plot reveals a large deviation from the diagonal, especially on the right side, implying that the distribution of residuals is not normally distributed. This makes sense due to the $40 error, where any prices exceeding $40 would be rounded down to $40, which caused a spike in the residuals around the ceiling. In addition, a fan shape can be seen in the residual plot, indicating heteroscedasticity, thus breaking another essential assumption of linear regression models, mainly due to the inability to predict values beyond $40.</p>
<p>Avery’s data manipulations lead to these problems. The&nbsp;$40 price cap&nbsp;created a ceiling effect, which compressed the response variable and distorted the residual distribution and variance. Since the genre_code is a categoric variable but is modeled as a numeric one, the model used one regression line for an intrinsically categorical variable. As such, there will be structured misfit within the residuals, because genres with different price categories have been lumped up together to give rise to greater residual variances. Dividing by 100 rather than 60 results in a scaling problem of around 40%. Although there is no direct regression violation here, the pt_hrs coefficient becomes meaningless, making any business conclusion drawn from it invalid.</p>
</section>
<section id="b3-the-fix-version-2.0" class="level2">
<h2 class="anchored" data-anchor-id="b3-the-fix-version-2.0">B3: The Fix – Version 2.0</h2>
<section id="step-1-build-best_practice_clean" class="level3">
<h3 class="anchored" data-anchor-id="step-1-build-best_practice_clean">Step 1: Build best_practice_clean</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>best_practice_clean <span class="ot">&lt;-</span> raw <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Remove rows with zero price (same as Avery — correct)</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(price <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Remove rows with zero reviews (same as Avery — correct)</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(total_reviews <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># FIX — Replace NA metacritic_score values with 0 to retain these rows</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">metacritic_score =</span> <span class="fu">replace_na</span>(metacritic_score, <span class="dv">0</span>)) <span class="sc">|&gt;</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># FIX - Parse release_date and extract components and dont convert to character </span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">release_date  =</span> <span class="fu">dmy</span>(release_date),</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">release_day   =</span> <span class="fu">day</span>(release_date),</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">release_month =</span> <span class="fu">month</span>(release_date, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">TRUE</span>),</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">release_year  =</span> <span class="fu">year</span>(release_date)</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Standardise developer name to title case</span></span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">developer =</span> <span class="fu">str_to_title</span>(developer)) <span class="sc">|&gt;</span></span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Remove columns not needed</span></span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>name, <span class="sc">-</span>release_date, <span class="sc">-</span>developer_bio) <span class="sc">|&gt;</span></span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Count developer titles</span></span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_count</span>(developer, <span class="at">name =</span> <span class="st">"dev_titles"</span>) <span class="sc">|&gt;</span></span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a>  <span class="co"># FIX — Convert minutes to hours by dividing by 60</span></span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pt_hrs =</span> <span class="fu">round</span>(avg_playtime_mins <span class="sc">/</span> <span class="dv">60</span>, <span class="dv">2</span>)) <span class="sc">|&gt;</span></span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-32"><a href="#cb23-32" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create lpeak = log(peak_players), rounded to 2dp</span></span>
<span id="cb23-33"><a href="#cb23-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">lpeak =</span> <span class="fu">round</span>(<span class="fu">log</span>(peak_players), <span class="dv">2</span>)) <span class="sc">|&gt;</span></span>
<span id="cb23-34"><a href="#cb23-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-35"><a href="#cb23-35" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Round positive_ratio to integer</span></span>
<span id="cb23-36"><a href="#cb23-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">positive_ratio =</span> <span class="fu">round</span>(positive_ratio, <span class="dv">0</span>) <span class="sc">|&gt;</span> <span class="fu">as.integer</span>()) <span class="sc">|&gt;</span></span>
<span id="cb23-37"><a href="#cb23-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-38"><a href="#cb23-38" aria-hidden="true" tabindex="-1"></a>  <span class="co"># FIX — Remove arbitrary price cap entirely</span></span>
<span id="cb23-39"><a href="#cb23-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">price =</span> <span class="fu">round</span>(price, <span class="dv">2</span>)) <span class="sc">|&gt;</span></span>
<span id="cb23-40"><a href="#cb23-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-41"><a href="#cb23-41" aria-hidden="true" tabindex="-1"></a>  <span class="co"># FIX — Convert genre_code to factor</span></span>
<span id="cb23-42"><a href="#cb23-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">genre_code =</span> <span class="fu">factor</span>(genre_code)) <span class="sc">|&gt;</span></span>
<span id="cb23-43"><a href="#cb23-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-44"><a href="#cb23-44" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Reorder columns cleanly</span></span>
<span id="cb23-45"><a href="#cb23-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(appid, developer, release_day, release_month, release_year,</span>
<span id="cb23-46"><a href="#cb23-46" aria-hidden="true" tabindex="-1"></a>         genre, genre_code, price, total_reviews, positive_ratio,</span>
<span id="cb23-47"><a href="#cb23-47" aria-hidden="true" tabindex="-1"></a>         avg_playtime_mins, peak_players, metacritic_score, platforms,</span>
<span id="cb23-48"><a href="#cb23-48" aria-hidden="true" tabindex="-1"></a>         pt_hrs, lpeak, dev_titles)</span>
<span id="cb23-49"><a href="#cb23-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-50"><a href="#cb23-50" aria-hidden="true" tabindex="-1"></a><span class="co"># Check</span></span>
<span id="cb23-51"><a href="#cb23-51" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(best_practice_clean)</span>
<span id="cb23-52"><a href="#cb23-52" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(best_practice_clean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,441
Columns: 17
$ appid             &lt;dbl&gt; 100004, 100005, 100006, 100007, 100009, 100010, 1000…
$ developer         &lt;chr&gt; "Redkite", "Moonlight Games", "Thunderbyte", "Redkit…
$ release_day       &lt;int&gt; 22, 6, 18, 19, 9, 17, 22, 30, 21, 12, 7, 14, 1, 22, …
$ release_month     &lt;ord&gt; Apr, Nov, Mar, Oct, Nov, Dec, Jun, Dec, Jun, Mar, Ap…
$ release_year      &lt;dbl&gt; 2022, 2020, 2020, 2019, 2023, 2019, 2023, 2018, 2018…
$ genre             &lt;chr&gt; "Action", "Strategy", "Action", "Action", "RPG", "Si…
$ genre_code        &lt;fct&gt; 1, 3, 1, 1, 2, 4, 4, 5, 3, 1, 3, 4, 2, 1, 4, 5, 1, 1…
$ price             &lt;dbl&gt; 56.15, 50.03, 55.21, 62.76, 54.10, 61.38, 51.81, 36.…
$ total_reviews     &lt;dbl&gt; 1699, 562, 812, 966, 293, 435, 747, 948, 461, 465, 4…
$ positive_ratio    &lt;int&gt; 96, 82, 76, 93, 61, 85, 60, 56, 97, 99, 56, 83, 91, …
$ avg_playtime_mins &lt;dbl&gt; 909, 470, 912, 652, 1068, 279, 210, 936, 837, 422, 4…
$ peak_players      &lt;dbl&gt; 126, 462, 289, 318, 203, 228, 88, 181, 351, 752, 234…
$ metacritic_score  &lt;dbl&gt; 68.0, 71.0, 68.8, 96.7, 85.3, 98.9, 96.8, 65.1, 0.0,…
$ platforms         &lt;dbl&gt; 3, 1, 2, 1, 1, 1, 3, 3, 2, 3, 2, 1, 2, 1, 2, 2, 2, 3…
$ pt_hrs            &lt;dbl&gt; 15.15, 7.83, 15.20, 10.87, 17.80, 4.65, 3.50, 15.60,…
$ lpeak             &lt;dbl&gt; 4.84, 6.14, 5.67, 5.76, 5.31, 5.43, 4.48, 5.20, 5.86…
$ dev_titles        &lt;int&gt; 189, 195, 194, 189, 189, 176, 183, 195, 183, 189, 16…</code></pre>
</div>
</div>
</section>
<section id="step-2-explore-before-modelling" class="level3">
<h3 class="anchored" data-anchor-id="step-2-explore-before-modelling">Step 2: Explore Before Modelling</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Explore predictor relationships before fitting the model</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>best_practice_clean <span class="sc">|&gt;</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(price, genre_code, total_reviews, positive_ratio,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>         pt_hrs, peak_players, platforms) <span class="sc">|&gt;</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggpairs</span>(</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title   =</span> <span class="st">"V2.0 — Predictor Relationships Before Modelling"</span>,</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">colour =</span> genre_code)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="steam-game-pricing-analysis_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="step-3-fit-v2-model-and-compare-to-legacy" class="level3">
<h3 class="anchored" data-anchor-id="step-3-fit-v2-model-and-compare-to-legacy">Step 3: Fit V2 Model and Compare to Legacy</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit legacy model on student_clean</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> student_clean</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>legacy_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> genre_code <span class="sc">+</span> total_reviews <span class="sc">+</span> positive_ratio <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>                     pt_hrs <span class="sc">+</span> peak_players <span class="sc">+</span> platforms, <span class="at">data =</span> df)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit V2 model on best_practice_clean</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="co"># genre_code is now a factor</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>v2_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> genre_code <span class="sc">+</span> total_reviews <span class="sc">+</span> positive_ratio <span class="sc">+</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>                 pt_hrs <span class="sc">+</span> peak_players <span class="sc">+</span> platforms,</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> best_practice_clean)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(legacy_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = price ~ genre_code + total_reviews + positive_ratio + 
    pt_hrs + peak_players + platforms, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-23.3959   0.2298   0.9416   1.5455   3.0379 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    35.6700453  0.8268431  43.140  &lt; 2e-16 ***
genre_code     -0.1870398  0.0773133  -2.419  0.01579 *  
total_reviews   0.0002945  0.0004187   0.703  0.48210    
positive_ratio  0.0229455  0.0081576   2.813  0.00504 ** 
pt_hrs          0.0107251  0.0344319   0.311  0.75552    
peak_players    0.0014917  0.0006751   2.210  0.02744 *  
platforms       0.6662794  0.1488922   4.475 8.84e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.151 on 745 degrees of freedom
Multiple R-squared:  0.04853,   Adjusted R-squared:  0.04087 
F-statistic: 6.334 on 6 and 745 DF,  p-value: 1.637e-06</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(v2_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = price ~ genre_code + total_reviews + positive_ratio + 
    pt_hrs + peak_players + platforms, data = best_practice_clean)

Residuals:
     Min       1Q   Median       3Q      Max 
-25.6320  -5.4235  -0.0339   5.4880  25.7947 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    28.9231048  1.4500233  19.947  &lt; 2e-16 ***
genre_code2     8.9973194  0.6125567  14.688  &lt; 2e-16 ***
genre_code3     6.6857016  0.6438131  10.385  &lt; 2e-16 ***
genre_code4     3.4703971  0.6223262   5.576 2.93e-08 ***
genre_code5    -3.9287595  0.6620014  -5.935 3.69e-09 ***
total_reviews   0.0003887  0.0007160   0.543    0.587    
positive_ratio  0.1139637  0.0146460   7.781 1.37e-14 ***
pt_hrs          0.0284833  0.0375553   0.758    0.448    
peak_players    0.0048972  0.0012280   3.988 7.00e-05 ***
platforms       3.3278884  0.2706047  12.298  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.995 on 1431 degrees of freedom
Multiple R-squared:  0.3099,    Adjusted R-squared:  0.3056 
F-statistic: 71.41 on 9 and 1431 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="step-4-polished-v2-plot" class="level3">
<h3 class="anchored" data-anchor-id="step-4-polished-v2-plot">Step 4: Polished V2 Plot</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create V2 plot</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>best_practice_clean <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> total_reviews, <span class="at">y =</span> price)) <span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">colour =</span> price), <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="fu">aes</span>(<span class="at">group =</span> <span class="dv">1</span>), <span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> release_month) <span class="sc">+</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_viridis_c</span>() <span class="sc">+</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">title    =</span> <span class="st">"SteamScope V2.0 — Price vs Community Size by Release Month"</span>,</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Fixed pipeline: correct units, no price cap"</span>,</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x        =</span> <span class="st">"Total Reviews"</span>,</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y        =</span> <span class="st">"Price (USD)"</span></span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="steam-game-pricing-analysis_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="b4-model-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="b4-model-interpretation">B4: Model Interpretation</h2>
<p>Genre 2 has the highest prices, of approximately $8.99 higher than the base genre, followed by Genre 3 (+$6.69) and Genre 4 (+$3.47). Genre 5 has the lowest prices, of about $3.93 lower than the base genre. This shows clearly different prices depending on genre, where some have been classified as high-end genres while others low-budget ones.</p>
<p>From the regression output above, we saw that the predictors genre, positive_ratio, peak_players, and platforms were significant predictors at p-value &lt; 0.05. Therefore, game pricing is mainly dependent on factors like quality perception (positive reviews), popularity (peak players), distribution channels (platforms) and genre of the game. Whereas, total_reviews and playtime hours are not significant, meaning only engagement volume does not impact pricing decisions for developers.</p>
<p>R² coefficient of 0.31 means that the model explains about 31 percent of the game price variation. While the model provides information regarding important factors of the game price, a significant percentage of variation is yet to be explained due to other factors such as brand reputation and marketing strategy.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1><strong>Conclusion</strong></h1>
<p>This analysis successfully reconstructed SteamScope’s original pricing pipeline, identified critical data quality issues, and developed an improved Version 2.0 workflow following data analytics best practices. The audit demonstrated that several transformation decisions in the original pipeline reduced model reliability by introducing data distortion, sampling bias, and incorrect variable handling. After correcting these issues, the improved model provided a more reliable understanding of the factors associated with game pricing, increasing explanatory power from R² = 0.049 to R² = 0.310.</p>
<p>The findings suggest that pricing decisions are influenced by factors such as game genre, player engagement, review sentiment, and platform availability. However, the model still explains only part of the variation in pricing, indicating that additional factors such as brand strength, marketing strategy, and market positioning should be considered before making final pricing recommendations. Overall, this project highlights the importance of reproducible data pipelines, data quality validation, and statistically sound modelling in producing trustworthy business insights.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>